config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views


app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('checkout/', views.checkout, name='checkout')
]

store/models.py
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField


class TimeStampedModel(models.Model):
    """
    Bazaviy model bo'lishi uchun TimeStampedModel yaratildi.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """
        Abstract=True yaratilishini maqsadi ma'lumotlar ba'zasida model yaratilmasligini taminlaydi.
        """
        abstract = True


class Category(TimeStampedModel):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def str(self):
        return self.name


class Product(TimeStampedModel):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True, blank=True)
    docs = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='product_img/', blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    digital = models.BooleanField(default=False, null=True, blank=True)

    def str(self):
        return self.name

    @property
    def image_url(self):
        try:
            url = self.image.url
        except:
            url = ''

        return url

    @property
    def total_count(self):
        return None


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def str(self):
        return self.name


class Order(TimeStampedModel):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def str(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(TimeStampedModel):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, blank=True, null=True)

    def str(self):
        return self.product.name

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(TimeStampedModel):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)

    def str(self):
        return self.address

store/views.py
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404

from store.models import *


# Create your views here.
def store(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'store/store.html', context)


def detail(request, pk):
    products = get_object_or_404(Product, pk=pk)
    context = {
        "product": products
    }
    return render(request, 'store/detail.html', context)


def cart(request):
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(complete=False)
        items = order.orderitem_set.all()
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}

    context = {'items': items, 'order': order}
    return render(request, 'store/cart.html', context)


def checkout(request):
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(complete=False)
        items = order.orderitem_set.all()
    else:
        # Create empty cart for now for non-logged in user
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}

    context = {'items': items, 'order': order}
    return render(request, 'store/checkout.html', context)

store/templates/store/cart.html
<!-- BASE -->
{% extends 'base.html' %}
{% load static %}
<!-- /BASE -->

<!-- Title -->
{% block title %} Cart {% endblock %}
<!-- /Title -->

<!-- CSS -->
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/cart.css' %}">
{% endblock %}
<!-- /CSS -->

<!-- BreadCrumbs -->
{% block breadcrumbs %}
    <li class="breadcrumb-item">
        <a class="link-body-emphasis fw-semibold text-decoration-none text-primary" href="{% url 'store:store' %}">
            <i class="bi bi-house-door-fill"></i>
            Store
        </a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
        Cart
    </li>
{% endblock %}
<!-- /BreadCrumbs -->

<!-- Content-->
{% block content %}

    <!-- Cart -->
    <div class="row mb-4">

        <!-- Total -->
        <div class="col-12 fs-5 sticky-top">
            <div class="shadow bg-white p-3 rounded">
                <!-- Back to Shopping -->
                <button class="btn btn-primary">
                    <a class="icon-link icon-link-hover fs-6 text-decoration-none link-hover-white"
                       style="--bs-icon-link-transform: translate(-0.325rem, 0); --bs-link-hover-color-rgb: white; --bs-link-color-rgb: yellow;"
                       href="{% url 'store:store' %}">
                        <svg class="bi" aria-hidden="true">
                            <i class="bi bi-arrow-left"></i>
                        </svg>
                        Back to Shopping
                    </a>
                </button>
                <!-- /Back to Shopping -->

                <br>

                <!-- Header Show Total Price -->
                <table class="table">
                    <tr>
                        <th style="border: none;  text-align: start;">Items: {{ order.get_cart_items }}</th>
                        <th style="border: none; text-align: start;">Total: ${{ order.get_cart_total }}</th>
                        <th style="border: none">
                            <a class="btn btn-success float-end icon-link icon-link-hover d-flex align-items-center"
                               href="{% url 'store:checkout' %}"
                               style="--bs-icon-link-transform: translate3d(0, -.125rem, 0); height: 3rem;">
                                <i class="bi bi-file-earmark-text"></i>
                                Checkout
                            </a>
                        </th>
                    </tr>
                </table>
                <!-- /Header Show Total Price -->
            </div>
        </div>
        <!-- /Total -->

        <!-- Product List -->
        <div class="col-12 my-3">
            <div class="shadow bg-white p-3 rounded">
                <!-- Header -->
                <div class="display-flex fs-6">
                    <div class="p-2 flex-1"></div>
                    <div class="p-2 flex-2 fw-bold">Items</div>
                    <div class="p-2 flex-1 fw-bold">Price</div>
                    <div class="p-2 flex-1 fw-bold">Quantity</div>
                    <div class="p-2 flex-1 fw-bold">Total</div>
                </div>
                <!-- /Header -->
                <br>
                <!-- Body -->
                {% for item in items %}
                <div class="display-flex bg-hover align-items-center">
                    <div class="p-2 flex-1 image-zoom">
                        <img class="img-fluid img_card object-fit-cover rounded"
                             src="{{ item.product.image_url }}" alt="rasm">
                    </div>
                    <div class="p-2 flex-2">{{ item.product.name }}</div>
                    <div class="p-2 flex-1">${{ item.product.price|floatformat:0 }}</div>
                    <div class="d-flex align-items-center p-2 flex-1">
                        <span>{{ item.quantity }}</span>
                        <span>
                        <div class="p-2">
                            <i class="bi bi-caret-up-fill"></i>
                            <br>
                            <i class="bi bi-caret-down-fill"></i>
                        </div>
                    </span>
                    </div>
                    <div class="p-2 flex-1">${{ item.get_total|floatformat:0}}</div>
                </div>
                {% endfor %}
                <!-- /Body -->
            </div>
        </div>
        <!-- /Product List -->
    </div>
    <!-- /Cart -->

{% endblock %}
<!-- /Content-->

store/templates/store/checkout.html
<!-- BASE -->
{% extends 'base.html' %}
{% load static %}
<!-- /BASE -->

<!-- Title -->
{% block title %} Checkout {% endblock %}
<!-- /Title -->

<!-- CSS -->
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/checkout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/cart.css' %}">
{% endblock %}
<!-- /CSS -->


<!-- BreadCrumbs -->
{% block breadcrumbs %}
    <li class="breadcrumb-item">
        <a class="link-body-emphasis fw-semibold text-decoration-none text-primary" href="{% url 'store:store' %}">
            <i class="bi bi-house-door-fill"></i>
            Store
        </a>
    </li>
    <li class="breadcrumb-item">
        <a class="link-body-emphasis fw-semibold text-decoration-none text-primary"
           href="{% url 'store:cart' %}">Cart</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
        Checkout
    </li>
{% endblock %}
<!-- /BreadCrumbs -->

<!-- Content -->
{% block content %}

    <!-- Checkout -->
    <div class="row">

        <!-- Col 1 Input Forms -->
        <div class="col-lg-6 my-2">
            <div class="shadow form-wrapper rounded p-3">
                <form action="" method="">
                    <!-- User info -->
                    <p class="fw-normal">User Information</p>
                    <div class="user-info">
                        <div class="form-field">
                            <input class="form-control" type="text" name="name" placeholder="Name...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="email" name="email" placeholder="Email...">
                        </div>
                    </div>
                    <!-- User info -->
                    <hr>
                    <!-- Shipping Information -->
                    <p class="fw-normal">Shipping Information</p>
                    <div class="shipping-info">
                        <div class="form-field">
                            <input class="form-control" type="text" name="address" placeholder="Place..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="city" placeholder="City..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="state" placeholder="State..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="zipcode" placeholder="ZipCode..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="zipcode" placeholder="ZipCode..">
                        </div>

                    </div>
                    <hr>
                    <button type="button" id="form-button" class="btn btn-success btn-block w-100">Continue</button>
                    <!-- /Shipping Information -->
                </form>
            </div>
            <br>

            <!-- PayPal -->
            <div class="shadow rounded text-center p-3 mb-3" id="payment-info">
                <i class="bi bi-paypal"></i> PayPal Options
            </div>
            <!-- /PayPal -->
        </div>
        <!-- /Col 1 Input Forms -->


        <!-- Col 2 Checkout Total -->
        <div class="col-lg-6 my-2">

            <div class="shadow rounded p-3 mb-4">
                <!-- Back to Shopping -->
                <button class="btn btn-outline-dark">
                    <a class="icon-link icon-link-hover fs-6 text-decoration-none link-hover-white"
                       style="--bs-icon-link-transform: translate(-0.325rem, 0); --bs-link-hover-color-rgb: white; --bs-link-color-rgb: yellow;"
                       href="{% url 'store:cart' %}">
                        <svg class="bi" aria-hidden="true">
                            <i class="bi bi-arrow-left"></i>
                        </svg>
                        Back
                    </a>
                </button>

                <button class="btn btn-primary">
                    <a class="icon-link icon-link-hover fs-6 text-decoration-none link-hover-white"
                       style="--bs-icon-link-transform: translate(-0.325rem, 0); --bs-link-hover-color-rgb: white; --bs-link-color-rgb: yellow;"
                       href="{% url 'store:store' %}">
                        <svg class="bi" aria-hidden="true">
                            <i class="bi bi-arrow-left"></i>
                        </svg>
                        Back to Shopping
                    </a>
                </button>
                <!-- /Back to Shopping -->

                <!-- Order Summary -->
                {% for item in items %}
                <hr>
                <p class="fs-5 fw-normal">Order Summary</p>
                <hr>
                <div class="d-flex bg-hover align-items-center">
                    <div class="flex-1">
                        <img class="img-fluid img_card object-fit-cover rounded"
                             src="{{item.product.image_url}}" alt="rasm">
                    </div>
                    <div class="flex-1">{{item.product.name}}</div>

                    <!-- Count up/down-->
                    <div class="d-flex align-items-center p-2 flex-1">
                        <span>{{item.quantity}}</span>
                        <span>
                        <div class="p-2 d-flex flex-column">
                            <i class="bi bi-caret-up-fill"></i>
                            <i class="bi bi-caret-down-fill"></i>
                        </div>
                    </span>
                    </div>
                    <!-- /Count up/down-->

                    <div class="flex-1">${{item.product.price}}</div>
                </div>
                {% endfor %}
                <!-- /Order Summary -->
                <hr>
                <h5>Items: {{order.get_cart_items}}</h5>
                <h5>Total: ${{order.get_cart_total}}</h5>
            </div>
        </div>
        <!-- /Col 2 Checkout Total -->
    </div>
    <!-- /Checkout -->

{% endblock %}
<!-- /Content -->

store/templates/store/detail.html
<!-- BASE -->
{% extends 'base.html' %}
<!-- /BASE -->

<!-- STATIC -->
{% load static %}
<!-- /STATIC -->

<!-- CSS -->
{% block style %}
    <link rel="stylesheet" href="{% static '/store/css/detail.css' %}">
{% endblock %}
<!-- /CSS -->

<!-- Title -->
{% block title %}
    Detail
{% endblock %}
<!-- /Title -->

<!-- BreadCrumbs -->
{% block breadcrumbs %}
    <li class="breadcrumb-item">
        <a class="link-body-emphasis fw-semibold text-decoration-none text-primary" href="{% url 'store:store' %}">
            <i class="bi bi-house-door-fill"></i>
            Store
        </a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
        Detail
    </li>
{% endblock %}
<!-- /BreadCrumbs -->

<!-- Content -->
{% block content %}
    {% if product %}
        <!-- Detail -->
        <div class="row mb-4">

            <!-- Detail Images -->
            <div class="col-6">
                <div class="row">
                    <!-- Vertical Images -->
                    <div class="col-2 img-large">
                        <img class="object-fit-cover" style="width: 80px; height: 90px;"
                             src="{{ product.image_url }}" alt="rasm">
                        <img class="object-fit-cover" style="width: 80px; height: 90px; margin-top: 10px;"
                             src="{{ product.image_url }}" alt="rasm">
                        <img class="object-fit-cover" style="width: 80px; height: 90px; margin-top: 10px;"
                             src="{{ product.image_url }}" alt="rasm">
                        <img class="object-fit-cover" style="width: 80px; height: 90px; margin-top: 10px;"
                             src="{{ product.image_url }}" alt="rasm">
                        <img class="object-fit-cover" style="width: 80px; height: 90px; margin-top: 10px;"
                             src="{{ product.image_url }}" alt="rasm">
                        <img class="object-fit-cover" style="width: 80px; height: 90px; margin-top: 10px;"
                             src="{{ product.image_url }}" alt="rasm">
                        <img class="object-fit-cover" style="width: 80px; height: 90px; margin-top: 10px;"
                             src="{{ product.image_url }}" alt="rasm">
                        <img class="object-fit-cover" style="width: 80px; height: 90px; margin-top: 10px;"
                             src="{{ product.image_url }}" alt="rasm">
                    </div>
                    <!-- /Vertical Images -->

                    <!-- Large One image -->
                    <div class="col-10 p-0">
                        <img class="img-large img-fluid object-fit-cover" src="{{ product.image_url }}"
                             alt="rasm">
                    </div>
                    <!-- /Large One image -->
                </div>
            </div>
            <!-- /Detail Images -->

            <!-- Detail Article -->
            <div class="col-6">
                <h3>{{ product.name }}</h3>
                <hr>
                {{ product.description }}
                <!-- Buttons -->
                <div class="box-element p-2">
                    <br>
                    <br>
                    <div class="display-flex flex-wrap">
                        <!-- Back to Shopping -->
                        <button class="btn btn-primary">
                            <a class="icon-link icon-link-hover fs-6 text-decoration-none link-hover-white"
                               style="--bs-icon-link-transform: translate(-0.325rem, 0); --bs-link-hover-color-rgb: white; --bs-link-color-rgb: yellow;"
                               href="{% url 'store:store' %}">
                                <svg class="bi" aria-hidden="true">
                                    <i class="bi bi-arrow-left"></i>
                                </svg>
                                Back to Shopping
                            </a>
                        </button>
                        <!-- /Back to Shopping -->

                        <!-- Add to Card -->
                        <button class="btn btn-outline-dark">Add to Card</button>
                        <!-- /Add to Card -->

                        <h4 style="display: inline-block; float: right">$ {{ product.price | floatformat:0 }}</h4>
                    </div>
                </div>
                <!-- /Buttons -->
            </div>
            <!-- /Detail Article -->


        </div>
        <!-- /Detail -->

        <hr>
        <span class="mx-3 fw-normal me-auto">Mahsulot tavsifi</span>
        <span class="mx-3 me-auto">Sharhlar (231) </span>
        <hr>

        <div class="mb-4">
            {{ product.docs | safe }}
        </div>

    {% else %}
        <div class="fs-1"> Product not found</div>
    {% endif %}

{% endblock %}
<!-- /Content -->

store/templates/store/store.html
<!-- BASE -->
{% extends 'base.html' %}
{% load static %}
<!-- /BASE -->

<!-- Title -->
{% block title %} Store {% endblock %}
<!-- /Title -->

<!-- CSS -->
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/store.css' %}">
{% endblock %}
<!-- /CSS -->

<!-- BreadCrumbs -->
{% block breadcrumbs %}
    <li class="breadcrumb-item active" aria-current="page">
        <i class="bi bi-house-door-fill"></i>
        Store
    </li>
{% endblock %}
<!-- /BreadCrumbs -->

<!-- Content -->
{% block content %}

    <!-- Store -->
    <div class="row">
        <!-- Store List -->
        {% for product in products %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
                <div class="image-zoom rounded">
                    <img class="img-focus img-fluid object-fit-cover"
                         src="{{ product.image_url }}" alt="rasm">
                </div>
                <div class="box-element p-2">
                    <b>{{ product.name }}</b>
                    <hr>
                    <div class="display-flex flex-wrap">
                        <button class="btn btn-outline-dark">Add to Card</button>
                        <button class="btn btn-warning"><a class="text-decoration-none"
                                                           href="{% url 'store:detail' product.id %}">View</a></button>
                        <h4 style="display: inline-block; float: right">$ {{ product.price | floatformat:0 }}</h4>
                    </div>
                </div>
            </div>
            <!-- /Store List -->
        {% endfor %}
    </div>
    <!-- /Store -->
{% endblock %}
<!-- /Content -->

templates/core/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Connect to us with social media:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Mars Commerce
          </h6>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="" class="text-reset">Everywhere</a>
          </p>
          <p>
            <a href="" class="text-reset">Everything</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="https://t.me/careerpy" class="text-reset" target="_blank">Telegram</a>
          </p>
          <p>
            <a href="https://www.instagram.com/uz_back_dev/" class="text-reset" target="_blank">Instagram</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> Tashkent, Yunusobod, 15-67-23</p>
          <p><i class="fas fa-print me-3"></i> + 998 91 177 91 16</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

{#  <!-- Copyright -->#}
{#  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">#}
{#    © 2024 Copyright:#}
{#    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MCB.com</a>#}
{#  </div>#}
{#  <!-- Copyright -->#}
</footer>
<!-- Footer -->

templates/core/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Mars Commerce</a>
        <!-- Basket -->
        <a type="button" class="btn btn-warning border-0 position-relative d-block d-sm-block d-md-block d-lg-none d-xl-none d-xxl-none" href="{% url 'store:cart' %}">
            <i class="bi bi-cart4"></i>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"> 0 </span>
        </a>
        <!-- /Basket -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <!-- User -->
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        Hello, {{ user.is_authenticated | default:'Guest' }}
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Login</a>
                        <a class="dropdown-item" href="#">Register</a>
                    </div>
                </li>
            </ul>
            <!-- /User -->

            <!-- Basket -->
            <a type="button" class="btn btn-warning border-0 position-relative d-none d-sm-none d-md-none d-lg-block d-xl-block d-xxl-block" href="{% url 'store:cart' %}">
                <i class="bi bi-cart4"></i>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"> 0 </span>
            </a>
            <!-- /Basket -->
        </div>

    </div>
</nav>
<!-- /Navbar -->